# Generated by Django 3.0.4 on 2020-06-13 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='no',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='employee number'),
        ),
    ]
