# Generated by Django 3.0.4 on 2020-06-13 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('work_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('serial_no', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break1', models.FloatField()),
                ('break2', models.FloatField()),
                ('start_break', models.TimeField()),
                ('end_break', models.TimeField()),
                ('status', models.TextField(default='')),
                ('remarks', models.TextField(default='')),
                ('report_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_report.WorkReport')),
            ],
        ),
    ]
