# Generated by Django 3.0.4 on 2020-06-13 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_report', '0005_auto_20200613_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreport',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='no'),
        ),
    ]
