# Generated by Django 3.0.4 on 2020-06-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_report', '0006_auto_20200613_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='workdetail',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_report.Status'),
        ),
    ]
