# Generated by Django 3.0.4 on 2020-06-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_report', '0007_auto_20200613_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
