# Generated by Django 3.0.4 on 2020-06-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_report', '0009_auto_20200613_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreport',
            name='project_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='site_work_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
