# Generated by Django 3.0.4 on 2020-07-12 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_report', '0011_auto_20200617_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreport',
            name='site_work_time',
            field=models.TextField(blank=True, default='0:00', null=True),
        ),
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('serial_no', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TextField(blank=True, default='9:00', null=True)),
                ('end_time', models.TextField(blank=True, default='18:00', null=True)),
                ('break1', models.TextField(blank=True, default='1:00', null=True)),
                ('break2', models.TextField(blank=True, default='0:00', null=True)),
                ('holidays', models.IntegerField(blank=True, default=96, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='no')),
            ],
        ),
    ]
