# Generated by Django 3.0.4 on 2020-09-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_report', '0013_reportsettings_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workreport',
            old_name='site_work_time',
            new_name='_site_work_time',
        ),
    ]
